Feature/hex img component
PlatformOfTrust/react-elements-of-trust pull request #39
Opened 2019-08-05 12:25 UTC by kumardennis

2019-08-12 08:05 UTC, edanchenkov reviewed
@kumardennis Could you add a comprehensive example to storybooks? E.g. how this component can look like in different context with different props/states. You can check here https://github.com/PlatformOfTrust/react-elements-of-trust/pull/37/files

2019-08-14 09:25 UTC, edanchenkov commented on stories/index.js
> +    <Image src="https://i.pinimg.com/originals/aa/49/54/aa4954451f16847cb657e68e5f46538a.jpg"/>
Maybe add local image instead?

2019-08-14 09:26 UTC, edanchenkov requested changes

2019-08-14 09:26 UTC, edanchenkov commented on stories/index.js
> +                    'https://penasultra.com/wp-content/plugins/webp-express/test/test-pattern-tv.jpg'
Maybe add local image instead?

2019-08-14 09:26 UTC, edanchenkov commented on stories/index.js
> +                    'https://penasultra.com/wp-content/plugins/webp-express/test/test-pattern-tv.jpg'
Maybe add local image instead?

2019-08-14 09:59 UTC, edanchenkov commented on stories/index.js
> +                    require('./../src/Components/Image/test.jpg')
This image should be in storybook folder `stories`. Components should not contain any test files.

2019-08-20 13:26 UTC, victorv-sbp approved these changes
Just a quick note here: generally, it's not good practice to merge a branch into another if the merged branch is not approved or considered stable.

2019-08-20 13:26 UTC, victorv-sbp commented on src/Components/HexImage/styles.scss
> +.hexTop,
You should use hyphen instead of camel case for css class names.

2019-08-21 08:09 UTC, merged